### ISSUE TITLE
Constraints.in file was missing 

### ISSUE THREAD

**Issue by a-abdoman** [GHeinzelmann/BAT.py#20]
First of all, thanks for providing such convenient scripts for FE calculation.

Right now, I repeated the test calculation of BRD4 examples, with all default settings.
I have successfully run the equal and fe calculations for pose0.
Then I ran the python BAT.py -i input-dd.sh -s analysis, there is an error message.
It located the place, in BAT/libanalysis.py, line 56. 
The restraints.dat file, which should be generated by cpptraj -I restraints.in command. 
But I could not find the restraints.in file.

I use Centos 7.6, the default python2.7.5, amber20 and the new BAT2.0 for the calculation. 
I use the GPU2080TI card with coda-11.1. 

Thanks very much for your help.

**Comment by GHeinzelmann** [comment]
Hi, you are welcome, and thanks for contacting me with possible issues with the code. This really helps improving it and fixing any issues that might appear.

BAT.py was written for use with python 3.8, and there are a few differences from python 2.7.5. Since you have AMBER20, I suggest using the miniconda version of python 3.8 from AMBER, as explained in the Equilibration section of the tutorial:

$AMBERHOME/miniconda/bin/python BAT.py -i input-dd.in -s analysis

Let me know if you are still having problems after running it like above. Best,

Germano

**Comment by GHeinzelmann** [comment]
Oh, I remembered one more thing, make sure cpptraj is in your path before running the analysis, which is done by running your amber.sh file beforehand.

**Comment by a-abdoman** [comment]
Thanks for your suggestion.
Yes, It works, after I use the new version of python (3.7.5, I don't have 3.8). 
The calculation finished normally. 
I will try it more.
