### ISSUE TITLE
suggestion: remove CONECT lines from protonated ligand files

### ISSUE THREAD

**Issue by camattelaer** [GHeinzelmann/BAT.py#36]
Hi 

I have encountered the same issue as previously posted (eg #31 and #30 amongst others). 

LEaP fails because the aromatic carbons are identified in the mol2 as `c3` atoms (aliphatic). This happens due to incorrect `CONECT` lines in the protonated lig-h.pdb:
```
...
CONECT    7    5    8    8                                            
CONECT    8    1    7    7    9                                       
CONECT    9    8   10   10   14                                       
**CONECT   10    9    9   11   21**                                       
CONECT   11   10   12   12   22                                       
CONECT   12   11   11   13   23                                       
CONECT   13   12   14   14   24                                       
CONECT   14    9   13   13   25                                       
CONECT   15    1   16   26                 
...
```
I have in general had better experience running antechamber when the protonated pdb consists only of `ATOM` lines. If i remove all of these `CONECT`lines and run antechamber manually, C9 has an aromatic atom type of `ca`.

Kind regards

Charles-Alexandre

**Comment by GHeinzelmann** [comment]
Hi Charles, and thanks for your interest in the BAT code. The CONECT lines should not be there, since I remove them from the initially protonated ligand. The part of the code that does this is located in line 157 of the BAT/lib/build.py script. 

Perhaps you are using an older version of the code? If not, please confirm that the ligand file (lig-h.pdb) that goes into the antechamber command (line 180 of the BAT/lib/build.py script) really has these CONECT lines in the pdb file. Thanks.

**Comment by camattelaer** [comment]
Hi 

Thanks for your reply. I took the BAT 2.2 version from the release page. (i usually do this so i can have a quick local download and this is usually the 'stable' release)

It is indeed missing the for-loop which gathers the `ATOM` or `HETATM` records. I simply did the same thing yesterday (although via a subprocess call to `sed`) and it enabled to run the 2.2 version. 

Closing this issue since it has already been implemented in the newer version.

Thank you for your time and kind regards!

CA
