### ISSUE TITLE
Confused about setting l1_x, l1_y, l1_z

### ISSUE THREAD

**Issue by ErikZhang-9762** [GHeinzelmann/BAT.py#40]
Hi,

I read the BAT user guide. In the manual, l1_x, l1_y, l1_z are described as:
```
l1_x, l1_y and l1_z: distances in the three Cartesian axes between the first protein anchor atom
P1 and the center of the search range for the L1 anchor, denoted by the r vector (see section 4.3). 
```
I use the geometric centre of the ligand as one point and P1 as the other, compute the r-vector and then xyz the r-vector as l1_x, l1_y, l1_z. BUT ERROR:
```
Ligand first anchor not found
Info) VMD for LINUXAMD64, version 1.9.3 (November 30, 2016)
Info) Exiting normally.
vmd >

WARNING: Could not find the ligand first anchor L1 for ['pose0']
The ligand is most likely not in the defined binding site in these systems.
```
How should I set l1_x, l1_y, l1_z?

Thanks,
Eric

**Comment by ErikZhang-9762** [comment]
I found the cause of the error: the distance between P1 and l1_x, l1_y, l1_z is greater than l1_range ( 4.5 Å).

Maybe P1 needs to be chosen for residues closer to ligand? Within 4.5 Å?

But the distance vector r between P1 and L1  (left of Fig. 2) should have an absolute value between 7 Å and 12 Å ?

I'm a little confused about this.😢

**Comment by ErikZhang-9762** [comment]
Another question， BAT will removes non-standard amino acids? I want to keep ACE and NME. Is there any way to do that?

**Comment by GHeinzelmann** [comment]
Hi, and thanks for your interest in the BAT code. Not sure if what you said about the P1-L1 distance and l1 range makes sense, it could be something else. I suggest reading the instructions carefully in the UG.

About the distance between L1 and P1, it should not be too short to avoid large forces applied on angles/torsions due to a small lever arm. And not too large that they allow too much displacement for a given angle/dihedral restraint. Also it has to be larger that l1 range.

I am not sure about these aminoacids, if they are included in the amber protein force field it might work. You can just try having them in the receptor and check if they are still there in the simulation files.

I am closing the issue, please contact me by email if needed.

**Comment by ErikZhang-9762** [comment]
I've addressed both of these issues, which are, in fact, interrelated. I've written the solution below in the hope that it will help others.

Firstly, the key point of the problem is that BAT uses VMD's tcl to process the input protein file.

and in `BAT/build_files/split-ini.tcl` 

line 3: `set prot [atomselect 0 "protein"]`, This will not select ACE and NME. So, the numbering order of the amino acids changes. 

Then, the P1, P2, and P3 defined in the input file are not actually the amino acids I want to select. This results in the ligand anchor not being able to be selected within 4.5 angstroms.

Edit the line 3 to `set prot [atomselect 0 "protein or resname ACE NME"]`, solves both problems.

There may be the same problem for membrane protein systems, I have not tested this, but if there is a similar problem, you can refer to this.

**Comment by GHeinzelmann** [comment]
Nice to see that it worked with different amino acids, I might have tested that at some point but don't recall it specifically. Thanks for sharing this solution!
