### ISSUE TITLE
kinase acetonitrile system

### ISSUE THREAD

**Issue by DDGmichigan** [GHeinzelmann/BAT.py#6]
Thanks I will need some guidance to set up the APR method on my kinase ligand system and I will provide details in a few minutes. Any help will be deeply appreciated @GHeinzelmann.
Regards

**Comment by GHeinzelmann** [comment]
OK, the program also uses double decoupling now, which makes it more widely applicable. I am happy to help you setting up your system, kinases should work with BAT.py.

**Comment by DDGmichigan** [comment]
Hello @GHeinzelmann ,
This is  the exact system I am working on, its  ABL kinase (3KFA.pdb)
Using a co-solvent based approach, I have certain x,y,z locations of a set of small molecules (ethanol, isopropanol, acetonitrile, phenol, pyridine etc) and I am interested to compute the absolute free energy of binding of these small probes to my kinase. All I know is locations ( in terms of x y z coordinates)  where the probe  density is maximum, that is, places on the protein where the probe sticks to it.
Paper details of the MixMD approach published  https://pubs.acs.org/doi/pdf/10.1021/acs.jcim.8b00925
So, given that information, how to modify my input files so that I can set up BAT.py to compute free energies of binding. I wanted to mention these are small  molecules ( all < 15 atoms) and are weak binders, so the range I am looking at is  ~ -2 to -4 kcal/mol at max.

**Comment by GHeinzelmann** [comment]
OK I actually have the parameters for that system already, so I could send them to you. The binding site is set up in the same position of the ligand in the 3fka structure, is it the same place where your molecules bind? About the affinities, 2-4 kcal/mol is not very high, what happens in this case is that the ligand could spontaneously leave the binding site during equilibration or during the attachment steps. ABFE calculations rely on the fact the ligand has a well-defined free energy minimum in the bound state, so that the approximations that we make in terms of sampling are valid in this regime. This is because we cannot sample the whole phase space, so if the fully coupled ligand is not stably bound this can bring problems during the calculations.

**Comment by DDGmichigan** [comment]
@GHeinzelmann  I have 4 sites on the 3KFA.pdb where there acetonitrile sticks to it and I am trying to calculate ABFE of these acetonitrile molecules.
Yes they are weak binders and I have already used the MD simulations to calculate k-on k-off rates also.
I can send you the PDB  files of the ABL kinase ACN complex system. Cant we restrain a ACN to the point and carry out the BAT py calculation?

I am sending pdb files of ACN complexed to my 3KFA.pdb at 2 places on the kinase surface.
[ACN_3KFA.zip.zip](https://github.com/GHeinzelmann/BAT.py/files/4933637/ACN_3KFA.zip.zip)

**Comment by DDGmichigan** [comment]
Can you set up the system and let me know the steps you took to set them up?
Inside the zip folder, there are 2 pdb files happy_SITE2.pdb and happy_SITE3.pdb
 There are 2 more sites on the protein where the ACN binds.
I want to know the steps to compute the ABFE for ACN binding to the protein.
I  have 4 different small molecules also to carry out the ABFE calculations all weak binders to 3KFA.pdb

**Comment by GHeinzelmann** [comment]
OK, as long as the ligand is stable in the binding site during the simulations for at least 100 ns there should not be a problem. I'll set up a system for you and send back the associated files. In section 6 of the user guide I explain how to set up a new system, have you seen that part? Maybe you can also give it a go, and I can help you if you have problems.

**Comment by DDGmichigan** [comment]
@GHeinzelmann  I am having issues setting up the system!
Could you set up one system I sent you the pdb file and then I can use it as the skeleton to set up all my systems.
Thanks
I appreciate your help in this regard

**Comment by GHeinzelmann** [comment]
Yes sure, sorry I was finishing a few other things but now I could get to your system. OK, so acetonitrile is a very unique molecule in which it only has three heavy atoms, and they are almost aligned, with an angle close to 180 degrees between them. That brings problems to a three ligand anchor setup, mostly due to gimbal locking. This can be avoided, but it would take a few adjustments to the restraint part of the code.  
How about we start with a different molecule, such as ethanol or phenol? Anyone is fine except ACN, for the reasons stated above. You can send me the bound system, and then I send the needed files for these molecules, as we were doing initially with ACN.

**Comment by DDGmichigan** [comment]
Sure, I have systems with isopropanol I can send them to you today @GHeinzelmann  Thanks so much Prof.
Regards

**Comment by GHeinzelmann** [comment]
OK, I'll get right to it then! :)

**Comment by DDGmichigan** [comment]
ABL kinase IPA bound in 2 sites so I have attached 2 pdbs for those 2  bound complexes.
[ABL_IPA_systems.zip](https://github.com/GHeinzelmann/BAT.py/files/4968572/ABL_IPA_systems.zip)

**Comment by GHeinzelmann** [comment]
OK I have set up the files for the first system. I am attaching a tarball with my last version BAT.py code adjusted for your complex. A few comments:

- The ligand seems to have stayed in the binding site during the 60 ns equilibration simulations, even though it does move around quite a bit. Might be harder to sample all the possible positions from the bound ligand, I suggest increasing the simulation time for the TR restraints windows.
- I removed the end residues from the receptor, which were modified residues I believe. Not sure if you need them, but if you do you may need additional parameters, which are easy to include in the BAT workflow once you have them. Your complex is located in the all-poses folder.
- There is a new variable called amber_version, where you should choose the amber version you want to use (amber18 or amber20). This is the updated version of the code already compatible with amber20, which I will publish on GitHub soon. 
- The simulation times for the different steps you can define by doing some testing, now they are set up a little shorter than the GitHub example. I usually look at the results from the block data analysis to check for convergence.
- In addition to the protein anchors, a few other changes in the input file include the l1_x, l1_y variables, and I also deactivated the rec_bb option, since it might not be needed for your system. I have changed the min_adis and max_adis options, since you have a very small ligand. 
- There is a new reference.pdb file inside the build_files folder, which has the correct alignment for the protein anchors to work properly. How to create this file is explained in the user guide, but I have already done that for your system. 
- Also in the build_files folder, I have modified the prep-crystal.tcl script, so it correctly cleans the complex pdb file before the building of the system. It uses VMD, so to understand it it is good to be familiar with VMD commands. 

As stated above, you can find more info in the user guide, which also explains how to set up a new protein system. A different binding site, such as your other IPA system, requires a new setup. I can also help you with any questions you have. 

[BAT-3kfa.tar.gz](https://github.com/GHeinzelmann/BAT.py/files/4975945/BAT-3kfa.tar.gz)

**Comment by DDGmichigan** [comment]
Hello @GHeinzelmann  Prof, I am so grateful to you for setting up a sample system for my studies, I will definitely work with the tar.gz you have provided and ask you questions on the way if that is fine with you.
Sometimes, a sample can go a long way in setting up more advanced systems, so I cannot thank you enough for the time you have given to make the files. I will update you as soon as I work with this folder. Thanks again.

**Comment by GHeinzelmann** [comment]
Hopefully that worked well. Closing issue.
